### ISSUE TITLE
Dosn't the c2cr util deserves a standalone repo and shard ?

### ISSUE THREAD

**Issue by bararchy** [ysbaddaden/clang.cr#1]
For me it's much cooler then the actual clang bindings :)

**Comment by ysbaddaden** [comment]
Probably, but it would depend on the `clang` shards anyway. I guess it should just be moved from `samples/` to `src/` and... properly tested. And a cool name, too.

**Comment by ysbaddaden** [comment]
I don't expect to remove the c2cr sample. It's a useful & detailed sample to understand libclang.
